<?php
ob_start();
include('../config/connect.php');
require('../fpdf/fpdf.php');

class CustomPDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 24);
        $this->SetTextColor(50, 50, 50);
        $this->Cell(0, 25, 'Returned Books Report', 0, 1, 'C');
        $this->SetDrawColor(11, 94, 43);
        $this->SetLineWidth(0.5);
        $this->Line(20, 30, 190, 30);
        $this->SetFont('Arial', 'I', 12);
        $this->Cell(0, 10, 'Generated on: ' . date('F d, Y'), 0, 1, 'C');
        $this->SetY(55);
    }

    function Footer() {
        for($i = 0; $i < 15; $i++) {
            $this->SetFillColor(11 + ($i/2), 94 + ($i/2), 43 + ($i/2));
            $this->Rect(0, 282 - $i, 210, 1, 'F');
        }
        $this->SetY(-15);
        $this->SetFont('Arial', 'B', 9);
        $this->SetTextColor(255, 255, 255);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}  |  Generated by E-Book Library System', 0, 0, 'C');
    }
}

function generatePDF($searchTerm, $conn) {
    $sql = "SELECT * FROM returned_books
            WHERE title LIKE ? OR name LIKE ?";

    $stmt = $conn->prepare($sql);
    $stmt->bind_param('ss', $searchTerm, $searchTerm);
    $stmt->execute();
    $result = $stmt->get_result();

    $allData = [];
    while ($row = $result->fetch_assoc()) {
        $allData[] = $row;
    }

    $pdf = new CustomPDF('P', 'mm', 'A4');
    $pdf->AliasNbPages();
    $pdf->AddPage();

    $cols = [
        ['width' => 15, 'title' => 'No.'],
        ['width' => 60, 'title' => 'Title'],
        ['width' => 45, 'title' => 'Borrower'],
        ['width' => 30, 'title' => 'Borrow'],
        ['width' => 30, 'title' => 'Return']
    ];

    $rowNumber = 1;

    $pdf->SetFont('Arial', 'B', 10);
    $pdf->SetFillColor(11, 94, 43, 0.8);
    $pdf->SetTextColor(0, 0, 0);

    foreach ($cols as $col) {
        $pdf->Cell($col['width'], 10, $col['title'], 0, 0, 'C', true);
    }
    $pdf->Ln();

    $pdf->SetFont('Arial', '', 9);
    $pdf->SetDrawColor(11, 94, 43);
    $fill = false;

    foreach ($allData as $row) {
        $pdf->SetFillColor($fill ? 240 : 255);
        $pdf->Cell($cols[0]['width'], 8, $rowNumber++, 'B', 0, 'C', $fill);
        $pdf->Cell($cols[1]['width'], 8, $row['title'], 'B', 0, 'L', $fill);
        $pdf->Cell($cols[2]['width'], 8, $row['name'], 'B', 0, 'L', $fill);
        $pdf->Cell($cols[3]['width'], 8, date('d/m/Y', strtotime($row['borrow_date'])), 'B', 0, 'C', $fill);
        $pdf->Cell($cols[4]['width'], 8, date('d/m/Y', strtotime($row['return_date'])), 'B', 1, 'C', $fill);
        $fill = !$fill;
    }

    $pdf->Output('D', 'returned_books_report_' . date('Y-m-d') . '.pdf');
}

if (isset($_GET['download_pdf'])) {
    ob_clean();
    $searchTerm = "%" . (isset($_GET['search']) ? $_GET['search'] : '') . "%";
    generatePDF($searchTerm, $conn);
    exit;
}

$page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$limit = 10;
$offset = ($page - 1) * $limit;
$search = isset($_GET['search']) ? $_GET['search'] : '';
$searchTerm = "%$search%";

$sql = "SELECT * FROM returned_books
        WHERE title LIKE ? OR name LIKE ?
        LIMIT ? OFFSET ?";

$stmt = $conn->prepare($sql);
$stmt->bind_param('ssii', $searchTerm, $searchTerm, $limit, $offset);
$stmt->execute();
$result = $stmt->get_result();

$data = [];
while ($row = $result->fetch_assoc()) {
    $data[] = $row;
}

$countQuery = "SELECT COUNT(*) AS total
               FROM returned_books
               WHERE title LIKE ? OR name LIKE ?";

$stmtTotal = $conn->prepare($countQuery);
$stmtTotal->bind_param('ss', $searchTerm, $searchTerm);
$stmtTotal->execute();
$totalResult = $stmtTotal->get_result();
$totalRow = $totalResult->fetch_assoc();
$totalRecords = $totalRow['total'];
$totalPages = ceil($totalRecords / $limit);

include 'navbar.php';

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Returned Books</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style media="screen">
    .container-returned {
        max-width: 1200px;
        margin: 2rem auto;
        padding: 2rem;
        margin-bottom: 200px;
        background: white;
        border-radius: 8px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center;
        color: #000;
        margin-bottom: 2rem;
        font-size: 1.5rem;
        font-weight: 600;
    }

    .search-container-returned {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1rem;
        gap: 1rem;
    }

    .search-form-returned {
        display: flex;
        flex: 1;
        max-width: 600px;
    }

    #searchInput-returned {
        flex: 1;
        padding: 0.5rem 1rem;
        border: 1px solid #e2e8f0;
        border-radius: 6px 0 0 6px;
        font-size: 0.875rem;
    }

    .search-form-returned button {
        padding: 0.5rem 1rem;
        background: #F2AC60;
        color: white;
        border: none;
        border-radius: 0 6px 6px 0;
        cursor: pointer;
        font-size: 0.875rem;
    }

    .download-link-returned {
        display: inline-flex;
        align-items: center;
        padding: 0.5rem 1rem;
        background: #fff;
        color: #000;
        text-decoration: none;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        font-size: 0.875rem;
        gap: 0.5rem;
    }

    .download-link-returned:hover {
        background: #f8f9fa;
    }

    .table-container-returned {
        margin-top: 1rem;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        overflow-x: auto; /* Added horizontal scroll for mobile */
    }

    table {
        width: 100%;
        min-width: 800px; /* Ensures table is wide enough to scroll */
        border-collapse: collapse;
    }

    th {
        background: #f8f9fa;
        color: #64748b;
        font-weight: 500;
        text-align: left;
        padding: 0.75rem 1rem;
        font-size: 0.875rem;
        border-bottom: 1px solid #e2e8f0;
        white-space: nowrap; /* Prevent text wrapping */
    }

    td {
        padding: 0.75rem 1rem;
        border-bottom: 1px solid #e2e8f0;
        font-size: 0.875rem;
        color: #333;
        white-space: nowrap; /* Prevent text wrapping */
    }

    tr:last-child td {
        border-bottom: none;
    }

    .pagination-returned {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 1rem;
        padding: 1rem 0;
    }

    .pagination-button-returned {
        display: inline-flex;
        align-items: center;
        padding: 0.5rem 1rem;
        background: #fff;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        color: #000;
        text-decoration: none;
        font-size: 0.875rem;
    }

    .pagination-button-returned:hover:not(:disabled) {
        background: #f8f9fa;
    }

    .pagination-button-returned:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .pagination-info-returned {
        font-size: 0.875rem;
        color: #64748b;
    }

    .no-results-returned {
        text-align: center;
        padding: 2rem;
        color: #64748b;
        font-size: 0.875rem;
    }

    @media (max-width: 768px) {
        .container-returned {
            padding: 1rem;
            margin: 1rem;
        }

        .search-container-returned {
            flex-direction: column;
        }

        .search-form-returned {
            width: 100%;
            max-width: none;
        }

        .download-link-returned {
            width: 100%;
            justify-content: center;
        }
    }
    </style>
</head>
<body>
    <div class="container-returned">
        <h2>RETURNED BOOKS</h2>

        <div class="search-container-returned">
            <form method="GET" action="" class="search-form-returned">
                <input type="text" id="searchInput-returned" name="search" placeholder="Search books..." value="<?php echo htmlspecialchars($search); ?>">
                <button type="submit">Search</button>
            </form>
            <a href="?download_pdf=1&search=<?php echo urlencode($search); ?>" class="download-link-returned">
                <i class='bx bx-download'></i> Download Table as PDF
            </a>
        </div>

        <div class="table-container-returned">
            <table>
              <thead>
                  <tr>
                      <th>No.</th>
                      <th>Library ID</th>
                      <th>Title</th>
                      <th>Borrower Name</th>
                      <th>Borrow Date</th>
                      <th>Return Date</th>
                  </tr>
              </thead>
              <tbody>
                  <?php
                  if (!empty($data)) {
                    $rowNumber = $offset + 1;
                    foreach ($data as $row) {
                        echo "<tr>
                                <td>{$rowNumber}</td>
                                <td>{$row['member_id']}</td>
                                <td>{$row['title']}</td>
                                <td>{$row['name']}</td>
                                <td>{$row['borrow_date']}</td>
                                <td>{$row['return_date']}</td>
                            </tr>";
                        $rowNumber++;
                    }
                  } else {
                      echo "<tr><td colspan='6' class='no-results-returned'>No records found</td></tr>";
                  }
                  ?>
              </tbody>
            </table>
        </div>

        <div class="pagination-returned">
            <a href="?page=<?php echo $page - 1; ?>&search=<?php echo htmlspecialchars($search); ?>" class="pagination-button-returned" <?php if ($page <= 1) echo 'disabled'; ?>>
                Previous
            </a>
            <span class="pagination-info-returned">Page <?php echo $page; ?> of <?php echo $totalPages; ?></span>
            <a href="?page=<?php echo $page + 1; ?>&search=<?php echo htmlspecialchars($search); ?>" class="pagination-button-returned" <?php if ($page >= $totalPages) echo 'disabled'; ?>>
                Next
            </a>
        </div>
    </div>

    <script>
        let timeout;
        document.getElementById('searchInput-returned').addEventListener('keyup', function() {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                this.form.submit();
            }, 1000);  // Delay in milliseconds (e.g., 1000ms)
        });
    </script>
</body>
</html>

<?php
$stmt->close();
$stmtTotal->close();
$conn->close();
